remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme

title: Jack Chai's deep learning proof of concept page
description: Try these deep learning widget yourself!

author:
  name: Jack Chai
